fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: system
        types: [shell]
        exclude_types: [csh, tcsh]
        entry: shfmt
        args: [--write]

      - id: nixfmt
        name: nixfmt
        language: system
        types: [nix]
        entry: nixfmt

      - id: shellcheck
        name: shellcheck
        language: system
        types: [shell]
        require_serial: true
        entry: shellcheck
