fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: system
        types: [shell]
        exclude_types: [csh, tcsh]
        entry: shfmt
        args: [--write]

      - id: nixfmt
        name: nixfmt
        language: system
        types: [nix]
        entry: nixfmt

      - id: shellcheck
        name: shellcheck
        language: system
        types: [shell]
        require_serial: true
        entry: shellcheck

      - id: nix-flake-check
        name: nix-flake-check
        language: system
        types: [nix]
        pass_filenames: false
        entry: nix flake check

      - id: nix-eval
        name: nix-eval
        language: system
        types: [nix]
        entry: nix eval
        pass_filenames: false
        args: [.#default.drvPath]
