#!/usr/bin/env sh

: '
Copy files or directories with .example suffix to the same name without the suffix,
if the target file/directory does not exist.
'

# Dev Container
if [ ! -d '.devcontainer' ] && [ -d '.devcontainer.example' ]; then
  echo 'Linking .devcontainer to .devcontainer.example'
  ln --symbolic .devcontainer.example .devcontainer
fi

# VS Code
if [ ! -d '.vscode' ] && [ -d '.vscode.example' ]; then
  echo 'Linking .vscode to .vscode.example'
  ln --symbolic .vscode.example .vscode
fi

# .env
if [ ! -f '.env' ] && [ -f '.env.example' ]; then
  echo 'Copying .env.example from .env'
  cp --verbose --update=none .env.example .env
fi

# .envrc (direnv)
if [ ! -f '.envrc' ]; then
  if [ -f '.envrc.example' ]; then
    echo 'Copying .envrc.example from .envrc'
    cp --verbose --update=none .envrc.example .envrc
  else
    echo 'Creating new .envrc file'
    cat <<EOF >.envrc
# See https://direnv.net/man/direnv-stdlib.1.html for other useful functions

if [ ! "\$(is_devcontainer)" = "true" ]; then
  use flake
fi

dotenv_if_exists .env
EOF
  fi
fi

# Development environment management with Nix Flakes
# ? Previously used shell.nix (nix-shell) but changed to flake.nix
# ? for more flexible and reproducible environment management
if [ ! -f 'flake.nix' ]; then
  cat <<EOF >flake.nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            git
            gnumake
            pre-commit
          ];
          shellHook = ''

          '';
        };
      }
    );
}
EOF
fi
