#!/usr/bin/env bash

alias cdd='source cdd.sh'

alias ans='ansible'
alias d='docker'
alias gc='gcloud'
alias h='helm'
alias ic='istioctl'
alias K='k9s'
alias k='kubectl'
alias kk='kubectl kustomize'
alias mk='minikube'
alias pl='pulumi'
alias pls='pulumi stack'
alias tal='talosctl'
alias tf='tofu'
alias tg='terragrunt'
alias tp='telepresence'
alias vg='vagrant'
