name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: bats

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run unit tests
        run: |
          ./test/bats/bin/bats --verbose-run --recursive ./test/unit

  test-linux:
    name: Test (${{ matrix.platform }}, ${{ matrix.image }})
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - ubuntu-24.04-arm # TODO: ubuntu-latest-arm is not available yet
        image:
          - mcr.microsoft.com/devcontainers/base:2-ubuntu
          - mcr.microsoft.com/devcontainers/base:1-debian
          # TODO: Add more base images to test against (e.g. Fedora)

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run integration tests
        env:
          LINUX_TEST__BASE_IMAGE: ${{ matrix.image }}
        run: |
          ./test/bats/bin/bats --verbose-run --recursive ./test/integration/linux

  # TODO: test-macos
  # TODO: test-windows
