name: Sync with Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    name: Sync
    if: ${{ vars.SYNC_UPSTREAM != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git remote add --fetch upstream 'https://github.com/lasuillard/dotfiles.git'
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Show Git configuration
        run: |
          git remote --verbose
          git branch --all
          git config --list

      - name: Merge upstream
        run: |
          git merge upstream/main --allow-unrelated-histories
          git push origin ${{ github.ref }}
